"use client"

interface TermsAndConditionsProps {
  isOpen: boolean
  onClose: () => void
}

export function TermsAndConditions({ isOpen, onClose }: TermsAndConditionsProps) {
  if (!isOpen) return null

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="sticky top-0 bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 p-6 flex items-center justify-between">
          <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
            Terms and Conditions
          </h2>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200"
          >
            <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6 text-gray-700 dark:text-gray-300">
          <div className="bg-yellow-50 dark:bg-yellow-900/20 border-l-4 border-yellow-400 p-4">
            <p className="font-bold text-yellow-800 dark:text-yellow-200 mb-2">
              IMPORTANT NOTICE
            </p>
            <p className="text-sm text-yellow-700 dark:text-yellow-300">
              This service is provided FOR INFORMATIONAL AND ENTERTAINMENT PURPOSES ONLY.
              We assume NO RESPONSIBILITY for any decisions made based on content analyzed or generated by this system.
            </p>
          </div>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
              1. Acceptance of Terms
            </h3>
            <p className="text-sm leading-relaxed">
              By creating an account and using YouTube Content Analyzer (&quot;the Service&quot;), you unconditionally
              agree to be bound by these Terms and Conditions. If you do not agree to these terms, you must
              immediately cease use of the Service and delete your account.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
              2. No Warranties or Guarantees
            </h3>
            <div className="space-y-2 text-sm">
              <p className="font-semibold">THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND.</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>We make NO GUARANTEES about the accuracy, reliability, or completeness of any analysis, transcripts, or generated content</li>
                <li>We assume NO RESPONSIBILITY for errors, omissions, or inaccuracies in AI-generated analyses</li>
                <li>Content is for INFORMATIONAL AND ENTERTAINMENT PURPOSES ONLY</li>
                <li>You acknowledge that AI systems may produce incorrect, biased, or misleading information</li>
                <li>Any reliance on content from this Service is AT YOUR OWN RISK</li>
              </ul>
            </div>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
              3. Limitation of Liability
            </h3>
            <div className="space-y-2 text-sm">
              <p className="font-semibold">TO THE MAXIMUM EXTENT PERMITTED BY LAW:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>We shall NOT be liable for any direct, indirect, incidental, special, consequential, or exemplary damages</li>
                <li>This includes but is not limited to: loss of profits, data, goodwill, or other intangible losses</li>
                <li>We are NOT responsible for decisions made based on content analyzed or generated by the Service</li>
                <li>We are NOT liable for any damages arising from service interruptions, data loss, or security breaches</li>
                <li>Total liability shall not exceed the amount you paid for the Service in the past 12 months (currently $0)</li>
              </ul>
            </div>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
              4. Dispute Resolution and Arbitration
            </h3>
            <div className="space-y-2 text-sm">
              <p className="font-semibold">MANDATORY BINDING ARBITRATION:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Any dispute, claim, or controversy arising from these Terms shall be resolved through BINDING ARBITRATION</li>
                <li>You WAIVE your right to file a lawsuit in court</li>
                <li>You WAIVE your right to a jury trial</li>
                <li>You WAIVE your right to participate in class action lawsuits</li>
                <li>Arbitration shall be conducted under the rules of the American Arbitration Association (AAA)</li>
                <li>Each party shall bear their own costs and attorney fees</li>
                <li>Arbitration decisions are final and binding with very limited grounds for appeal</li>
                <li>The arbitrator may not award punitive or exemplary damages</li>
              </ul>
              <p className="font-semibold mt-3">MEDIATION REQUIREMENT:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Before arbitration, parties must attempt good-faith mediation for at least 30 days</li>
                <li>Mediation costs shall be split equally between parties</li>
              </ul>
            </div>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
              5. Data Collection and Use
            </h3>
            <div className="space-y-2 text-sm">
              <p className="font-semibold">BY USING THE SERVICE, YOU EXPLICITLY CONSENT TO:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Collection of all data you input, upload, or generate through the Service</li>
                <li>Use of your data to improve our systems, algorithms, and AI models</li>
                <li>Use of your data to train machine learning models and language models</li>
                <li>Aggregation and analysis of usage patterns and user behavior</li>
                <li>Retention of data indefinitely unless you request deletion</li>
                <li>Sharing of anonymized, aggregated data with third parties</li>
              </ul>
              <p className="mt-2">
                We collect: account information, video URLs analyzed, transcripts, AI analyses, usage patterns,
                IP addresses, browser information, and all interactions with the Service.
              </p>
            </div>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
              6. User Responsibilities
            </h3>
            <div className="space-y-2 text-sm">
              <ul className="list-disc pl-6 space-y-1">
                <li>You are solely responsible for verifying the accuracy of any information from the Service</li>
                <li>You must not use the Service for any illegal or unauthorized purpose</li>
                <li>You must not rely on AI-generated content for critical decisions without independent verification</li>
                <li>You acknowledge this is an experimental service and may contain bugs or errors</li>
                <li>You are responsible for maintaining the confidentiality of your account credentials</li>
              </ul>
            </div>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
              7. Intellectual Property
            </h3>
            <div className="space-y-2 text-sm">
              <ul className="list-disc pl-6 space-y-1">
                <li>By using the Service, you grant us a perpetual, irrevocable, worldwide, royalty-free license to use any content you submit</li>
                <li>This includes the right to modify, reproduce, distribute, and create derivative works</li>
                <li>You retain ownership of content you submit, but grant us broad usage rights</li>
              </ul>
            </div>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
              8. Service Modifications and Termination
            </h3>
            <div className="space-y-2 text-sm">
              <ul className="list-disc pl-6 space-y-1">
                <li>We may modify, suspend, or discontinue the Service at any time without notice</li>
                <li>We may terminate your account at any time for any reason without explanation</li>
                <li>We are not liable for any losses resulting from service changes or termination</li>
              </ul>
            </div>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
              9. Indemnification
            </h3>
            <p className="text-sm">
              You agree to indemnify, defend, and hold harmless the Service, its operators, affiliates, and partners
              from any claims, damages, losses, liabilities, and expenses (including attorney fees) arising from your
              use of the Service or violation of these Terms.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
              10. Governing Law
            </h3>
            <p className="text-sm">
              These Terms shall be governed by and construed in accordance with the laws of the State of Delaware,
              United States, without regard to its conflict of law provisions. The United Nations Convention on
              Contracts for the International Sale of Goods shall not apply.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
              11. Severability
            </h3>
            <p className="text-sm">
              If any provision of these Terms is found to be unenforceable, the remaining provisions shall remain
              in full force and effect. The unenforceable provision shall be modified to the minimum extent necessary
              to make it enforceable while preserving the original intent.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
              12. Entire Agreement
            </h3>
            <p className="text-sm">
              These Terms constitute the entire agreement between you and the Service regarding use of the platform.
              We may update these Terms at any time without notice. Continued use constitutes acceptance of modified Terms.
            </p>
          </section>

          <section className="bg-red-50 dark:bg-red-900/20 border-l-4 border-red-400 p-4">
            <p className="font-bold text-red-800 dark:text-red-200 mb-2">
              FINAL ACKNOWLEDGMENT
            </p>
            <p className="text-sm text-red-700 dark:text-red-300">
              BY ACCEPTING THESE TERMS, YOU ACKNOWLEDGE THAT:
            </p>
            <ul className="list-disc pl-6 mt-2 text-sm text-red-700 dark:text-red-300 space-y-1">
              <li>This service is for informational and entertainment purposes only</li>
              <li>You waive the right to sue in court and accept mandatory arbitration</li>
              <li>We assume no responsibility for decisions made using this Service</li>
              <li>Your data will be used to improve and train our systems</li>
              <li>You have read, understood, and agree to all terms above</li>
            </ul>
          </section>

          <div className="text-xs text-gray-500 dark:text-gray-400 mt-6 pt-6 border-t border-gray-200 dark:border-gray-700">
            <p>Last Updated: January 2, 2026</p>
            <p className="mt-2">Version 1.0</p>
          </div>
        </div>

        {/* Footer */}
        <div className="sticky bottom-0 bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 p-6">
          <button
            onClick={onClose}
            className="w-full px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-medium transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  )
}
